import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { OperationalOrderListItem, PaymentStatus } from "@velora/contracts";
import { veloraApi } from "../../core/api/veloraApi";
import { useAuthStore } from "../../core/auth/authStore";
import { useOperationalCompanyId } from "../../core/company/useOperationalCompany";
import { ConfirmDialog, type ConfirmDialogState } from "../../shared/feedback/ConfirmDialog";
import { Notice } from "../../shared/feedback/Notice";

export function OperationalOrdersPage() {
  const user = useAuthStore((state) => state.user)!; const companyId = useOperationalCompanyId(); const client = useQueryClient(); const [status, setStatus] = useState<"" | PaymentStatus>(""); const [search, setSearch] = useState(""); const [confirm, setConfirm] = useState<ConfirmDialogState | null>(null); const [message, setMessage] = useState<string | null>(null);
  const role = user.role as "ADMIN" | "STORE_MANAGER";
  const orders = useQuery({ queryKey: ["operational-orders", role, companyId], queryFn: () => veloraApi.operationalOrders(role, companyId ?? undefined), enabled: Boolean(companyId) });
  const filtered = useMemo(() => (orders.data ?? []).filter((order) => { const latest = order.payments[0]; return (!status || latest?.status === status) && (!search || `${order.orderNumber} ${order.customerName} ${order.storeName}`.toLowerCase().includes(search.toLowerCase())); }), [orders.data, status, search]);
  const refresh = async (text: string) => { setMessage(text); await client.invalidateQueries({ queryKey: ["operational-orders"] }); };
  const confirmPayment = useMutation({ mutationFn: (id: string) => veloraApi.confirmPayment(role, id, "Pago confirmado desde React Web."), onSuccess: () => refresh("Pago confirmado.") });
  const failPayment = useMutation({ mutationFn: (id: string) => veloraApi.failPayment(role, id, "Pago marcado como fallido desde React Web."), onSuccess: () => refresh("Pago marcado como fallido.") });
  const refundPayment = useMutation({ mutationFn: (id: string) => veloraApi.refundPayment(role, id, "Reembolso procesado desde React Web."), onSuccess: () => refresh("Pago reembolsado.") });
  const fulfill = useMutation({ mutationFn: (id: string) => veloraApi.fulfillOrder(role, id), onSuccess: () => refresh("Pedido entregado y SALE registrado.") });
  if (!companyId) return <section className="page"><Notice>Seleccione una compañía o espere la resolución del contexto de sucursal.</Notice></section>;
  return <section className="page"><div className="page-heading"><span className="eyebrow">PEDIDOS Y VENTAS</span><h1>Operación comercial</h1><p>Pagos, fulfillment y scope por Store validados nuevamente en NestJS.</p></div>{message ? <Notice kind="success">{message}</Notice> : null}<div className="toolbar"><input placeholder="Pedido, cliente, sucursal…" value={search} onChange={(event) => setSearch(event.target.value)} /><select value={status} onChange={(event) => setStatus(event.target.value as "" | PaymentStatus)}><option value="">Todos los pagos</option><option value="PENDING">PENDING</option><option value="PAID">PAID</option><option value="FAILED">FAILED</option><option value="CANCELLED">CANCELLED</option><option value="REFUNDED">REFUNDED</option></select></div><div className="orders-list">{filtered.map((order) => <OperationalCard key={order.id} order={order} onConfirm={(state) => setConfirm(state)} actions={{ confirmPayment: (id) => confirmPayment.mutateAsync(id), failPayment: (id) => failPayment.mutateAsync(id), refundPayment: (id) => refundPayment.mutateAsync(id), fulfill: (id) => fulfill.mutateAsync(id) }} />)}</div><ConfirmDialog state={confirm} onClose={() => setConfirm(null)} /></section>;
}

function OperationalCard({ order, onConfirm, actions }: { order: OperationalOrderListItem; onConfirm: (state: ConfirmDialogState) => void; actions: { confirmPayment: (id: string) => Promise<unknown>; failPayment: (id: string) => Promise<unknown>; refundPayment: (id: string) => Promise<unknown>; fulfill: (id: string) => Promise<unknown>; } }) {
  const latest = order.payments[0] ?? null; const paid = order.payments.find((payment) => payment.status === "PAID") ?? null;
  return <article className="order-card operational"><div className="order-header"><div><span className="status-pill">{order.status}</span><h2>{order.orderNumber}</h2><p>{order.customerName} · {order.customerEmail ?? "sin correo"}</p><small>{order.storeName} · {order.warehouseName} · {order.orderChannel}/{order.fulfillmentType}</small></div><div className="order-amount"><strong>{order.total.toFixed(2)} {order.currency}</strong><small>{new Date(order.createdAt).toLocaleString()}</small></div></div><div className="payment-area"><h3>Intentos de pago</h3>{order.payments.length ? order.payments.map((payment) => <div className="payment-row" key={payment.id}><span>{payment.method}</span><span className={`status-pill status-${payment.status.toLowerCase()}`}>{payment.status}</span><strong>{payment.amount.toFixed(2)} {payment.currency}</strong></div>) : <p>Sin pagos.</p>}</div><div className="actions">{latest?.status === "PENDING" && latest.provider !== "STRIPE" ? <><button className="button small" onClick={() => onConfirm({ title: "Confirmar pago", message: `Se marcará ${latest.method} como PAID.`, onConfirm: () => actions.confirmPayment(latest.id) })}>Confirmar pago</button><button className="button small danger-outline" onClick={() => onConfirm({ title: "Marcar pago fallido", message: "El pedido seguirá reservado y podrá registrar otro intento.", destructive: true, onConfirm: () => actions.failPayment(latest.id) })}>Fallido</button></> : null}{paid && order.status === "RESERVED" ? <><button className="button small primary" onClick={() => onConfirm({ title: "Completar pedido", message: "Se descontará stock físico y comprometido, se registrará SALE y el pedido pasará a FULFILLED.", onConfirm: () => actions.fulfill(order.id) })}>Entregar / Fulfill</button><button className="button small secondary" onClick={() => onConfirm({ title: "Reembolsar pago", message: "Solo es válido antes de la entrega. Para Stripe se utiliza el proveedor configurado.", destructive: true, onConfirm: () => actions.refundPayment(paid.id) })}>Reembolsar</button></> : null}</div></article>;
}
