import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { CustomerAddressRequest, CustomerAddressResponse, CustomerType, UserProfile } from "@velora/contracts";
import { veloraApi } from "../../core/api/veloraApi";
import { webPush, type WebPushEnableResult } from "../../core/push/webPush";
import { useAuthStore } from "../../core/auth/authStore";
import { ConfirmDialog, type ConfirmDialogState } from "../../shared/feedback/ConfirmDialog";
import { Notice } from "../../shared/feedback/Notice";

const blankAddress: CustomerAddressRequest = { label: "", recipientName: "", recipientPhone: "", department: "Santa Cruz", city: "Santa Cruz de la Sierra", zone: null, addressLine: "", reference: null, defaultAddress: false };

export function AccountPage() {
  const client = useQueryClient(); const replaceUser = useAuthStore((state) => state.replaceUser); const [message, setMessage] = useState<string | null>(null); const [confirm, setConfirm] = useState<ConfirmDialogState | null>(null); const [editing, setEditing] = useState<CustomerAddressResponse | null>(null);
  const profile = useQuery({ queryKey: ["customer-profile"], queryFn: veloraApi.customerProfile });
  const addresses = useQuery({ queryKey: ["addresses"], queryFn: veloraApi.addresses });
  const saveProfile = useMutation({ mutationFn: veloraApi.updateCustomerProfile, onSuccess: async (user) => { replaceUser(user); client.setQueryData(["customer-profile"], user); setMessage("Perfil actualizado."); } });
  const createAddress = useMutation({ mutationFn: veloraApi.createAddress, onSuccess: async () => { setMessage("Dirección guardada."); await client.invalidateQueries({ queryKey: ["addresses"] }); setEditing(null); } });
  const updateAddress = useMutation({ mutationFn: ({ id, body }: { id: string; body: CustomerAddressRequest }) => veloraApi.updateAddress(id, body), onSuccess: async () => { setMessage("Dirección actualizada."); await client.invalidateQueries({ queryKey: ["addresses"] }); setEditing(null); } });
  const deleteAddress = useMutation({ mutationFn: veloraApi.deleteAddress, onSuccess: () => client.invalidateQueries({ queryKey: ["addresses"] }) });
  const submitProfile = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget); const customerType = String(data.get("customerType")) as CustomerType;
    await saveProfile.mutateAsync({ firstName: String(data.get("firstName") ?? ""), lastName: String(data.get("lastName") ?? ""), phone: String(data.get("phone") ?? "") || null, customerType, businessName: customerType === "B2B" ? String(data.get("businessName") ?? "") || null : null, taxId: customerType === "B2B" ? String(data.get("taxId") ?? "") || null : null });
  };
  return <section className="page"><div className="page-heading"><span className="eyebrow">MI CUENTA</span><h1>Perfil y direcciones</h1><p>Datos que utilizamos para preparar y entregar sus pedidos.</p></div>{message ? <Notice kind="success">{message}</Notice> : null}{profile.data ? <ProfileForm key={`${profile.data.id}-${profile.data.customerType}`} profile={profile.data} onSubmit={submitProfile} busy={saveProfile.isPending} /> : <div className="panel">Cargando perfil…</div>}<PushNotificationsPanel /><div className="section-heading small"><h2>Direcciones de entrega</h2></div><div className="address-grid">{addresses.data?.map((address) => <article className="address-card" key={address.id}><div><span className="eyebrow">{address.defaultAddress ? "PREDETERMINADA" : "DIRECCIÓN"}</span><h3>{address.label}</h3><p>{address.recipientName} · {address.recipientPhone}</p><p>{address.addressLine}, {address.zone ? `${address.zone}, ` : ""}{address.city}</p>{address.reference ? <small>{address.reference}</small> : null}</div><div className="actions"><button className="button small secondary" onClick={() => setEditing(address)}>Editar</button><button className="button small danger-outline" onClick={() => setConfirm({ title: `¿Eliminar ${address.label}?`, message: address.defaultAddress ? "Se asignará automáticamente otra dirección predeterminada si existe." : "La dirección dejará de estar disponible.", destructive: true, confirmLabel: "Eliminar", onConfirm: () => deleteAddress.mutateAsync(address.id) })}>Eliminar</button></div></article>)}</div><AddressForm editing={editing} onCancel={() => setEditing(null)} onSave={async (body) => { if (editing) await updateAddress.mutateAsync({ id: editing.id, body }); else await createAddress.mutateAsync(body); }} /><ConfirmDialog state={confirm} onClose={() => setConfirm(null)} /></section>;
}

function ProfileForm({ profile, onSubmit, busy }: { profile: UserProfile; onSubmit: (event: FormEvent<HTMLFormElement>) => Promise<void>; busy: boolean }) {
  const [type, setType] = useState<CustomerType>(profile.customerType ?? "B2C");
  return <form className="panel" onSubmit={(event) => void onSubmit(event)}><h2>Perfil</h2><div className="form-grid"><label>Nombre<input name="firstName" defaultValue={profile.firstName} required /></label><label>Apellido<input name="lastName" defaultValue={profile.lastName} required /></label><label>Teléfono<input name="phone" defaultValue={profile.phone ?? ""} maxLength={40} /></label><label>Tipo de cliente<select name="customerType" value={type} onChange={(event) => setType(event.target.value as CustomerType)}><option value="B2C">B2C · Persona</option><option value="B2B">B2B · Empresa</option></select></label>{type === "B2B" ? <><label>Razón social<input name="businessName" defaultValue={profile.businessName ?? ""} required maxLength={160} /></label><label>NIT<input name="taxId" defaultValue={profile.taxId ?? ""} required maxLength={40} /></label></> : null}</div><button className="button primary" disabled={busy}>{busy ? "Guardando…" : "Guardar perfil"}</button></form>;
}

function AddressForm({ editing, onCancel, onSave }: { editing: CustomerAddressResponse | null; onCancel: () => void; onSave: (body: CustomerAddressRequest) => Promise<void> }) {
  const initial: CustomerAddressRequest = editing ? { label: editing.label, recipientName: editing.recipientName, recipientPhone: editing.recipientPhone, department: editing.department, city: editing.city, zone: editing.zone, addressLine: editing.addressLine, reference: editing.reference, defaultAddress: editing.defaultAddress } : blankAddress;
  const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { await onSave({ label: String(data.get("label") ?? ""), recipientName: String(data.get("recipientName") ?? ""), recipientPhone: String(data.get("recipientPhone") ?? ""), department: String(data.get("department") ?? ""), city: String(data.get("city") ?? ""), zone: String(data.get("zone") ?? "") || null, addressLine: String(data.get("addressLine") ?? ""), reference: String(data.get("reference") ?? "") || null, defaultAddress: data.get("defaultAddress") === "on" }); if (!editing) event.currentTarget.reset(); } finally { setBusy(false); } };
  return <form className="panel" key={editing?.id ?? "new"} onSubmit={(event) => void submit(event)}><h2>{editing ? `Editar ${editing.label}` : "Agregar dirección"}</h2><div className="form-grid"><label>Alias<input name="label" defaultValue={initial.label} required /></label><label>Destinatario<input name="recipientName" defaultValue={initial.recipientName} required /></label><label>Teléfono<input name="recipientPhone" defaultValue={initial.recipientPhone} required /></label><label>Departamento<input name="department" defaultValue={initial.department} required /></label><label>Ciudad<input name="city" defaultValue={initial.city} required /></label><label>Zona<input name="zone" defaultValue={initial.zone ?? ""} /></label><label className="span-2">Dirección<input name="addressLine" defaultValue={initial.addressLine} required /></label><label className="span-2">Referencia<input name="reference" defaultValue={initial.reference ?? ""} /></label><label className="checkbox"><input name="defaultAddress" type="checkbox" defaultChecked={initial.defaultAddress} />Usar como predeterminada</label></div><div className="actions">{editing ? <button type="button" className="button secondary" onClick={onCancel}>Cancelar edición</button> : null}<button className="button primary" disabled={busy}>{busy ? "Guardando…" : editing ? "Actualizar dirección" : "Guardar dirección"}</button></div></form>;
}

function PushNotificationsPanel() {
  const [result, setResult] = useState<WebPushEnableResult | null>(null);
  const enable = useMutation({ mutationFn: () => webPush.enableNotifications(), onSuccess: setResult });
  const message = result === "enabled" ? "Notificaciones activadas en este navegador." : result === "denied" ? "El navegador tiene bloqueadas las notificaciones." : result === "unsupported" ? "Este navegador no admite notificaciones push." : result === "error" ? "No fue posible registrar este navegador." : null;
  return <div className="panel"><h2>Notificaciones</h2><p>Reciba cambios de pedidos y pagos en este dispositivo.</p>{message ? <Notice kind={result === "enabled" ? "success" : "error"}>{message}</Notice> : null}<button className="button secondary" disabled={enable.isPending} onClick={() => enable.mutate()}>{enable.isPending ? "Activando…" : "Activar notificaciones"}</button></div>;
}
