import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { veloraApi } from "../../core/api/veloraApi";
import { useAuthStore } from "../../core/auth/authStore";
import { useCompanyStore } from "../../core/company/companyStore";
import { Notice } from "../../shared/feedback/Notice";

export function AdminDashboard() {
  const companyId = useCompanyStore((state) => state.adminCompanyId); const companies = useCompanyStore((state) => state.companies); const client = useQueryClient(); const [message, setMessage] = useState<string | null>(null);
  const stores = useQuery({ queryKey: ["admin-stores", companyId], queryFn: () => veloraApi.adminStores(companyId!), enabled: Boolean(companyId) });
  const managers = useQuery({ queryKey: ["admin-managers", companyId], queryFn: () => veloraApi.managers(companyId!), enabled: Boolean(companyId) });
  const createStore = useMutation({ mutationFn: veloraApi.createStore, onSuccess: async () => { setMessage("Sucursal creada correctamente."); await client.invalidateQueries({ queryKey: ["admin-stores"] }); } });
  const createManager = useMutation({ mutationFn: veloraApi.createManager, onSuccess: async () => { setMessage("Encargado creado y asignado correctamente."); await client.invalidateQueries({ queryKey: ["admin-managers"] }); } });
  const submitStore = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!companyId) return; const data = new FormData(event.currentTarget); await createStore.mutateAsync({ companyId, code: String(data.get("code") ?? ""), name: String(data.get("name") ?? ""), address: String(data.get("address") ?? "") || null }); event.currentTarget.reset(); };
  const submitManager = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!companyId) return; const data = new FormData(event.currentTarget); await createManager.mutateAsync({ companyId, storeId: String(data.get("storeId") ?? ""), firstName: String(data.get("firstName") ?? ""), lastName: String(data.get("lastName") ?? ""), email: String(data.get("email") ?? ""), password: String(data.get("password") ?? "") }); event.currentTarget.reset(); };
  return <section className="page"><div className="page-heading"><span className="eyebrow">ADMINISTRACIÓN</span><h1>Operación VÉLORA</h1><p>Company → Stores → Encargados. No se usan membresías intermedias.</p></div>{message ? <Notice kind="success">{message}</Notice> : null}{!companyId ? <Notice>Seleccione una compañía en el menú lateral. {companies.length > 1 ? "No se elegirá ninguna automáticamente." : ""}</Notice> : <><div className="metric-grid"><article><span>Sucursales</span><strong>{stores.data?.length ?? 0}</strong></article><article><span>Encargados</span><strong>{managers.data?.length ?? 0}</strong></article><article><span>Compañía</span><strong>{companies.find((company) => company.id === companyId)?.code ?? "—"}</strong></article></div><div className="two-columns"><form className="panel" onSubmit={(event) => void submitStore(event)}><h2>Nueva sucursal</h2><label>Código<input name="code" required maxLength={40} /></label><label>Nombre<input name="name" required maxLength={120} /></label><label>Dirección<input name="address" maxLength={240} /></label><button className="button primary" disabled={createStore.isPending}>Crear sucursal</button></form><form className="panel" onSubmit={(event) => void submitManager(event)}><h2>Nuevo encargado</h2><div className="form-grid"><label>Nombre<input name="firstName" required /></label><label>Apellido<input name="lastName" required /></label><label className="span-2">Correo<input name="email" type="email" required /></label><label>Contraseña temporal<input name="password" type="password" required minLength={8} /></label><label>Sucursal<select name="storeId" required><option value="">Seleccione</option>{stores.data?.filter((store) => store.active).map((store) => <option value={store.id} key={store.id}>{store.name}</option>)}</select></label></div><button className="button primary" disabled={createManager.isPending}>Crear encargado</button></form></div><div className="panel"><h2>Sucursales</h2><div className="table-wrap"><table><thead><tr><th>Código</th><th>Nombre</th><th>Dirección</th><th>Estado</th></tr></thead><tbody>{stores.data?.map((store) => <tr key={store.id}><td>{store.code}</td><td>{store.name}</td><td>{store.address ?? "—"}</td><td>{store.active ? "Activa" : "Inactiva"}</td></tr>)}</tbody></table></div></div><div className="panel"><h2>Encargados</h2><div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Correo</th><th>Sucursal</th><th>Estado</th></tr></thead><tbody>{managers.data?.map((manager) => <tr key={manager.id}><td>{manager.firstName} {manager.lastName}</td><td>{manager.email}</td><td>{manager.storeName}</td><td>{manager.status}</td></tr>)}</tbody></table></div></div></>}</section>;
}

export function ManagerDashboard() {
  const user = useAuthStore((state) => state.user); const company = useCompanyStore((state) => state.managerCompany);
  return <section className="page"><div className="page-heading"><span className="eyebrow">SUCURSAL</span><h1>{user?.storeName ?? "Mi sucursal"}</h1><p>{company?.name ?? "Compañía derivada desde su sucursal asignada"}. El alcance se valida nuevamente en NestJS.</p></div><div className="metric-grid"><Link to="/sucursal/catalogo"><span>Catálogo</span><strong>Gestionar</strong></Link><Link to="/sucursal/inventario"><span>Inventario</span><strong>Revisar</strong></Link><Link to="/sucursal/pedidos"><span>Pedidos</span><strong>Operar</strong></Link></div></section>;
}
